version: 0.2
phases:
  pre_build:
    commands:
    - echo Logging in...
    #- aws codeartifact login --tool npm --repository reeple --domain reeple --domain-owner $AWS_ACCOUNT_ID --region $AWS_DEFAULT_REGION
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 698276559677.dkr.ecr.us-east-1.amazonaws.com
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - REPOSITORY_URI=698276559677.dkr.ecr.us-east-1.amazonaws.com/nodejs-webapp
    - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$COMMIT_HASH"'@' deployment.yml
    
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t 698276559677/nodejs-webapp:latest .
    #- docker build -t $ECR_REGISTRY:$COMMIT_HASH .
    - docker tag 698276559677/nodejs-webapp:latest $REPOSITORY_URI:$COMMIT_HASH

  post_build:
    commands:
    - echo Build completed on `date`
    - docker push $REPOSITORY_URI:$COMMIT_HASH
    #- cp 698276559677.dkr.ecr.us-east-1.amazonaws.com/nodejs-webapp:$COMMIT_HASH >> https://github.com/ccjacobs14/helm-project/blob/bdc8c2ffd40e1fde07a6c3620207abd4b43a5c41/myawesomeapp14/prod-values.yaml
    #- sed -i 's@CONTAINER_IMAGE@'"698276559677.dkr.ecr.us-east-1.amazonaws.com/nodejs-webapp:$COMMIT_HASH"'@' https://github.com/ccjacobs14/helm-project/blob/main/myawesomeapp14/prod-values.yaml
    - printf '[{"name":"node-pipeline","imageUri":"%s"}]' $REPOSITORY_URI:$COMMIT_HASH > build.json
artifacts:
  files: build.json
