version: 0.2
phases:
  pre_build:
    commands:
    - echo Logging in...
    #- aws codeartifact login --tool npm --repository reeple --domain reeple --domain-owner $AWS_ACCOUNT_ID --region $AWS_DEFAULT_REGION
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 698276559677.dkr.ecr.us-east-1.amazonaws.com
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t 698276559677/nodejs-webapp:latest .
    - docker tag 698276559677/nodejs-webapp:latest 698276559677.dkr.ecr.us-east-1.amazonaws.com/nodejs-webapp:$COMMIT_HASH

  post_build:
    commands:
    - echo Build completed on `date`
    - docker push 698276559677.dkr.ecr.us-east-1.amazonaws.com/nodejs-webapp:$COMMIT_HASH
    - cp 698276559677.dkr.ecr.us-east-1.amazonaws.com/nodejs-webapp:$COMMIT_HASH >> https://github.com/ccjacobs14/helm-project/blob/bdc8c2ffd40e1fde07a6c3620207abd4b43a5c41/myawesomeapp14/prod-values.yaml
    #- sed -i 's@CONTAINER_IMAGE@'"698276559677.dkr.ecr.us-east-1.amazonaws.com/nodejs-webapp:$COMMIT_HASH"'@' https://github.com/ccjacobs14/helm-project/blob/bdc8c2ffd40e1fde07a6c3620207abd4b43a5c41/myawesomeapp14/prod-values.yaml

    #- printf '[{"name":"pipeline name","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_HASH > imagedefinitions.json
  #artifacts:
    #files: imagedefinitions.json
